### ISSUE TITLE
Cannot set the breakpoint for file from included path when restart debug session

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/java-debug#24]
Project: https://github.com/fbricon/vscode-java-demo
System: Ubuntu

1. Git clone the project
2. Open with VSCode and wait for the project initialized with language server
3. Config launch.json
4. Start debugging

Issue:  
1. Debug into SpringApplication which is not part of the workspace but in the included path
2. Set a breakpoint on the SprintApplication
3. Restart debug session. 

Cannot set the breakpoint for SpringApplication

```console
[Error - 11:22:49 PM] Sep 13, 2017 11:21:52 PM DebugSession dispatch exception:java.lang.IllegalStateException
[Error - 11:37:19 PM] Sep 13, 2017 11:21:52 PM File not found: '/vscode-java-demo/SpringApplication.java'
Resource '/vscode-java-demo/SpringApplication.java' does not exist.
org.eclipse.core.internal.resources.ResourceException: Resource '/vscode-java-demo/SpringApplication.java' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:335)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:209)
	at org.eclipse.core.internal.resources.File.getContents(File.java:275)
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1190)
	at org.eclipse.jdt.internal.core.CompilationUnit.getContents(CompilationUnit.java:652)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1125)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:813)
	at com.microsoft.java.debug.plugin.internal.JdtSourceLookUpProvider.getFullyQualifiedName(JdtSourceLookUpProvider.java:103)
	at com.microsoft.java.debug.core.adapter.handler.SetBreakpointsRequestHandler.convertClientBreakpointsToDebugger(SetBreakpointsRequestHandler.java:110)
	at com.microsoft.java.debug.core.adapter.handler.SetBreakpointsRequestHandler.handle(SetBreakpointsRequestHandler.java:76)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:72)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:201)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.processData(ProtocolServer.java:171)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.start(ProtocolServer.java:95)
	at com.microsoft.java.debug.plugin.internal.JavaDebugServer$2.run(JavaDebugServer.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


```

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "mainClass": "com.redhat.vscode.demo.DevoxxApplication",
            "args": "",
            "sourcePaths": [
                "${workspaceRoot}"
            ]
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 0,
            "timeout": 30000,
            "sourcePaths": [
                "${workspaceRoot}"
            ]
        }
    ]
}
```
![error](https://user-images.githubusercontent.com/17268517/30413350-0d8aa34c-9950-11e7-9279-f11cf331f0b5.png)

**Comment by testforstephen** [comment]
fixed.
