### ISSUE TITLE
Debug adapter process has terminated unexpectedly (read ECONNRESET)

### ISSUE THREAD

**Issue by googlomooglo** [microsoft/java-debug#242]
Java debugger randomly terminates when debut attach with the following error:
Debug adapter process has terminated unexpectedly (read ECONNRESET)

The following is the logs from the dev tools console:
notificationsAlerts.ts:40 Debug adapter process has terminated unexpectedly (read ECONNRESET)
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:223
t.notify @ notifications.ts:113
t.error @ notificationService.ts:48
(anonymous) @ debugService.ts:511
e.fire @ event.ts:223
(anonymous) @ debugSession.ts:749
e.fire @ event.ts:223
t.fireAdapterExitEvent @ rawDebugSession.ts:460
(anonymous) @ rawDebugSession.ts:439
Promise resolved (async)
t.stopAdapter @ rawDebugSession.ts:438
(anonymous) @ rawDebugSession.ts:426
Promise rejected (async)
t.shutdown @ rawDebugSession.ts:422
(anonymous) @ rawDebugSession.ts:79
e.fire @ event.ts:223
(anonymous) @ debugAdapter.ts:281
emitOne @ events.js:116
emit @ events.js:211
emitErrorNT @ internal/streams/destroy.js:64
_combinedTickCallback @ internal/process/next_tick.js:138
_tickCallback @ internal/process/next_tick.js:180
console.ts:134 [Extension Host] rejected promise not handled within 1 second (at Timeout.<anonymous> (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:760:9))
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:451
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
log.ts:169   ERR Running the contributed command:'java.execute.workspaceCommand' failed.: Error: Running the contributed command:'java.execute.workspaceCommand' failed.
	at e._executeContributedCommand (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:497:869)
	at e.executeCommand (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:497:95)
	at Object.executeCommand (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:659)
	at Object.executeJavaLanguageServerCommand (C:\Users\user_name\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.15.0\out\src\commands.js:19:28)
	at fetchUsageData (C:\Users\user_name\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.15.0\out\src\extension.js:98:21)
	at vscode.debug.onDidTerminateDebugSession (C:\Users\user_name\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.15.0\out\src\extension.js:37:9)
	at e.fire (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
	at e.$acceptDebugSessionTerminated (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:515:765)
	at t._doInvokeHandler (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:652:708)
	at t._invokeHandler (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:652:380)
	at t._receiveRequest (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:650:971)
	at t._receiveOneMessage (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:649:900)
	at c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:647:733
	at c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:130:793
	at e.fire (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
	at a (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:185:760)
	at Socket.n._socketDataListener (c:\Users\user_name\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:185:981)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "",
            "args": ""
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        }
    ]
}

**Comment by testforstephen** [comment]
@googlomooglo could you share the reproduce steps for us to investigation?
