### ISSUE TITLE
error on continue request: Got IOException from Virtual Machine 

### ISSUE THREAD

**Issue by andxu** [Microsoft/java-debug#33]
The overall log is :

{"type":"request","seq":1,"command":"launch","arguments":{"cwd":"/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance","mainClass":"VariablePerfTest","classPaths":["/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance/bin"],"sourcePaths":["/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance/src/main/java"]}}
Sep 19, 2017 8:38:46 AM Trying to launch Java Program with options "-Dfile.encoding=UTF-8 -cp [Ljava.lang.String;@429d3448 VariablePerfTest " .
Sep 19, 2017 8:38:46 AM Launching debuggee VM succeeded.
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 77

{"success":true,"request_seq":1,"command":"launch","seq":1,"type":"response"}
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":2,"command":"setBreakpoints","arguments":{"lines":[4],"breakpoints":[{"line":4}],"source":{"path":"/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance/src/main/java/TooManyVariables.java"}}}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 157

{"success":true,"request_seq":2,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":true,"line":4,"message":""}]},"seq":2,"type":"response"}
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":3,"command":"configurationDone"}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 88

{"success":true,"request_seq":3,"command":"configurationDone","seq":3,"type":"response"}
Sep 19, 2017 8:38:46 AM 
JDI Event: VMStartEvent: 0

Sep 19, 2017 8:38:46 AM 
JDI Event: ThreadStartEvent: 5

Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 98

{"event":"thread","body":{"reason":"started","threadId":1,"type":"thread"},"seq":4,"type":"event"}
Sep 19, 2017 8:38:46 AM 
JDI Event: ClassPrepareEvent: 3

Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 149

{"event":"breakpoint","body":{"reason":"new","breakpoint":{"id":1,"verified":true,"line":4,"message":""},"type":"breakpoint"},"seq":5,"type":"event"}
Sep 19, 2017 8:38:46 AM 
JDI Event: BreakpointEvent: 7

Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 129

{"event":"stopped","body":{"threadId":1,"reason":"breakpoint","allThreadsStopped":false,"type":"stopped"},"seq":6,"type":"event"}
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":4,"command":"stackTrace","arguments":{"threadId":1}}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 600

{"success":true,"request_seq":4,"command":"stackTrace","body":{"stackFrames":[{"id":1,"source":{"name":"TooManyVariables.java","path":"/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance/src/main/java/TooManyVariables.java","sourceReference":0},"line":4,"column":0,"name":"test"},{"id":2,"source":{"name":"VariablePerfTest.java","path":"/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/testcase/7.variableperformance/src/main/java/VariablePerfTest.java","sourceReference":0},"line":3,"column":0,"name":"main"}],"totalFrames":2},"seq":7,"type":"response"}
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":5,"command":"threads"}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 258

{"success":true,"request_seq":5,"command":"threads","body":{"threads":[{"id":2,"name":"Thread [Signal Dispatcher]"},{"id":3,"name":"Thread [Finalizer]"},{"id":4,"name":"Thread [Reference Handler]"},{"id":1,"name":"Thread [main]"}]},"seq":8,"type":"response"}
***threads { threads: 
   [ { id: 2, name: 'Thread [Signal Dispatcher]' },
     { id: 3, name: 'Thread [Finalizer]' },
     { id: 4, name: 'Thread [Reference Handler]' },
     { id: 1, name: 'Thread [main]' } ] }
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":6,"command":"scopes","arguments":{"frameId":1}}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 155

{"success":true,"request_seq":6,"command":"scopes","body":{"scopes":[{"name":"Local","variablesReference":3,"expensive":false}]},"seq":9,"type":"response"}
***scopes { scopes: [ { name: 'Local', variablesReference: 3, expensive: false } ] }
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":7,"command":"variables","arguments":{"variablesReference":3}}
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 231

{"success":true,"request_seq":7,"command":"variables","body":{"variables":[{"name":"this","value":"TooManyVariables (id\u003d409)","type":"TooManyVariables","variablesReference":4,"indexedVariables":0}]},"seq":10,"type":"response"}
Sep 19, 2017 8:38:46 AM 
[REQUEST]
{"type":"request","seq":8,"command":"continue","arguments":{"threadId":1}}
Sep 19, 2017 8:38:46 AM 
JDI Event: ThreadDeathEvent: 6

Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 120

{"event":"output","body":{"category":"stdout","output":"variable perf test.\n","type":"output"},"seq":11,"type":"event"}
Sep 19, 2017 8:38:46 AM 
JDI Event: ThreadStartEvent: 5

**** variable perf test.

Sep 19, 2017 8:38:46 AM 
JDI Event: ThreadDeathEvent: 6

Sep 19, 2017 8:38:46 AM 
JDI Event: VMDeathEvent: 0

Sep 19, 2017 8:38:46 AM 
JDI Event: VMDisconnectEvent: 0

Sep 19, 2017 8:38:46 AM DebugSession dispatch exception:com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 207

{"success":false,"message":"Got IOException from Virtual Machine","request_seq":8,"command":"continue","body":{"error":{"id":1000,"format":"Got IOException from Virtual Machine"}},"seq":12,"type":"response"}
Error: Got IOException from Virtual Machine
    at /var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/node_modules/vscode-debugadapter-testsupport/lib/protocolClient.js:36:35
    at DebugClient.ProtocolClient.dispatch (/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/node_modules/vscode-debugadapter-testsupport/lib/protocolClient.js:98:17)
    at DebugClient.ProtocolClient.handleData (/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/node_modules/vscode-debugadapter-testsupport/lib/protocolClient.js:64:30)
    at Socket.<anonymous> (/var/lib/jenkins/workspace/vscode-java-debug-vsix-test/ci/node_modules/vscode-debugadapter-testsupport/lib/protocolClient.js:25:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    1) should pass variable performance test.
(node:48804) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Got IOException from Virtual Machine
Sep 19, 2017 8:38:46 AM 
[[RESPONSE]]
Content-Length: 98

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/104
