### ISSUE TITLE
Tests failing on mac

### ISSUE THREAD

**Issue by ChristianChiarulli** [microsoft/java-debug#404]
I am getting 43 errors in tests and it's failing on:

```
Java Debug Server for Visual Studio Code :: Debugger Core FAILURE
```

My java version is:

```
openjdk 11.0.2 2019-01-15
```

For more context it builds and works fine on Linux.

**Comment by testforstephen** [comment]
pls provide more error info.

**Comment by ChristianChiarulli** [comment]
```-------------------------------------------------------------------------------

Test set: com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest

-------------------------------------------------------------------------------

Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.646 sec <<< FAILURE!

testAcceptType(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.084 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testToString(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.081 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testDefaultOptions(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.079 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testValueOf(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.082 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testValueOfNotSupported(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.082 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testValueOfNotIllegalInput(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.08 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testToHexOctString(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.078 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

 

testToStringNotSupported(com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest)  Time elapsed: 0.079 sec  <<< ERROR!

java.lang.NullPointerException

                at com.microsoft.java.debug.core.AbstractJdiTestCase.waitForBreakPointEvent(AbstractJdiTestCase.java:41)

                at com.microsoft.java.debug.core.adapter.BaseJdiTestCase.setup(BaseJdiTestCase.java:36)

                at com.microsoft.java.debug.core.adapter.formatter.NumericFormatterTest.setup(NumericFormatterTest.java:40)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

                at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)

                at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

                at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

                at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

                at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

                at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

                at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.base/java.lang.reflect.Method.invoke(Method.java:566)

                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)```

I'm getting null pointer exceptions for pretty much every test

**Comment by shale-bw** [comment]
I am running into the same issue with 43 failing tests while building the Debugger Core. Looking at the stack trace for the tests I am also receiving NullPointerExceptions

Java version:
openjdk 11.0.15 2022-04-19

**Comment by shale-bw** [comment]
I am happy to provide more information as is necessary, please just let me know what you need for this. I have attached some more information about my system preemptively
![Screen Shot 2022-05-31 at 9 06 18 AM](https://user-images.githubusercontent.com/105666481/171206630-409efdff-3a78-4f5b-ae01-9a7689fa8bfd.png)

**Comment by sa82trip** [comment]
I'm facing same issue on my mac too. 🥲

**Comment by scottrbrtsn** [comment]
Running `./mvnw clean install` threw java version mismatch error for me with java-11.  

Tests passed with java 17. 

¯\_(ツ)_/¯

**Comment by ChristianChiarulli** [comment]
yea it works now with 17, so I guess this can be closed
