### ISSUE TITLE
Bundle com.microsoft.java.debug.plugin - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11

### ISSUE THREAD

**Issue by asmodeus812** [microsoft/java-debug#405]
Hello, I am getting the following error when trying to run mvnw clean install on my machine, i am using jdk 17, and i was unable to find anyone with a similar issue or resolve it myself. Here is the relevant part of the log 

`.local/share/nvim/lsp_extensions/java-debug/com.microsoft.java.debug.plugin/pom.xml
[ERROR] Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle com.microsoft.java.debug.plugin cannot be resolved
[ERROR] Resolution errors:
[ERROR]    Bundle com.microsoft.java.debug.plugin - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle com.microsoft.java.debug.plugin cannot be resolved
Resolution errors:
   Bundle com.microsoft.java.debug.plugin - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11

        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:60)
Caused by: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle com.microsoft.java.debug.plugin cannot be resolved
Resolution errors:
   Bundle com.microsoft.java.debug.plugin - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11

        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:266)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath(OsgiBundleProject.java:164)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:140)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:267)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        ... 18 more
Caused by: org.osgi.framework.BundleException: Bundle com.microsoft.java.debug.plugin cannot be resolved
Resolution errors:
   Bundle com.microsoft.java.debug.plugin - Missing Constraint: Bundle-RequiredExecutionEnvironment: JavaSE-11

        at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved(EquinoxResolver.java:306)
        at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState(EquinoxResolver.java:75)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:263)
        ... 24 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
asmodeus@Asmodeus:~/.local/share/nvim/lsp_extensions/java-debug$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)
asmodeus@Asmodeus:~/.local/share/nvim/lsp_extensions/java-debug$`

**Comment by LudvigHz** [comment]
Downgrading to `0.34.0` seemed to fix this for me.

------
```
$ uname -a
Linux xps-hoz 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux

$ Java  -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+3)
OpenJDK 64-Bit Server VM (build 17.0.3+3, mixed mode)

**Comment by asmodeus812** [comment]
@LudvigHz downgrading what to 0.34 ? The language server (jdtls) ? or java-debug ?

**Comment by testforstephen** [comment]
@asmodeus812 Coud you try to set your **JAVA_HOME** environment variables to JDK 11? Maven command line tool is based on JAVA_HOME env to find Java executable.
