### ISSUE TITLE
Failed to build on Java 11 or Java 17.

### ISSUE THREAD

**Issue by qianweichun** [microsoft/java-debug#419]
It is Mac OS 12.4, with Oracle Java11 and Java17, to build version 0.37.0, and 0.3x.0s
Error to build on Java 11?
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.microsoft.java.debug.plugin 0.37.0
[ERROR]   Missing requirement: org.eclipse.jdt.ls.core 1.13.0.202206080005 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=17))' but it could not be found
[ERROR]   Cannot satisfy dependency: com.microsoft.java.debug.plugin 0.37.0 depends on: osgi.bundle; org.eclipse.jdt.ls.core 0.0.0
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: com.microsoft.java:com.microsoft.java.debug.plugin:0.37.0 @ /Users/qianwch/.local/share/jc.nvim/vendor/java-debug/com.microsoft.java.debug.plugin/pom.xml: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

Error to build on Java 17?
```
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /Users/qianwch/.m2/repository/p2/osgi/bundle/org.eclipse.jdt.ls.core/1.13.0.202206080005/org.eclipse.jdt.ls.core-1.13.0.202206080005.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-17' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /Users/qianwch/.m2/repository/p2/osgi/bundle/org.eclipse.jdt.ls.core/1.13.0.202206080005/org.eclipse.jdt.ls.core-1.13.0.202206080005.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-17'
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:122)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:60)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /Users/qianwch/.m2/repository/p2/osgi/bundle/org.eclipse.jdt.ls.core/1.13.0.202206080005/org.eclipse.jdt.ls.core-1.13.0.202206080005.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-17'
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments(OsgiManifest.java:69)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.<init>(OsgiManifest.java:55)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parse(OsgiManifest.java:152)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromFile(DefaultBundleReader.java:82)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest(DefaultBundleReader.java:61)
	at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest(DefaultBundleReader.java:50)
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.loadManifest(EquinoxResolver.java:269)
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.newState(EquinoxResolver.java:161)
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState(EquinoxResolver.java:69)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:263)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath(OsgiBundleProject.java:164)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:140)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:267)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	... 18 more
Caused by: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'JavaSE-17'
	at org.eclipse.tycho.core.ee.ExecutionEnvironmentUtils.getExecutionEnvironment(ExecutionEnvironmentUtils.java:87)
	at org.eclipse.tycho.core.osgitools.OsgiManifest.parseExecutionEnvironments(OsgiManifest.java:66)
	... 33 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by qianweichun** [comment]
It seems that the reason to fail is that jdt.ls has just moved to Java17.
The work-around is to use maven mirror to point jdt to milestone version, add the following to $HOME/.m2/settings.xml:
```
  <mirror>
    <id>JDT.LS</id>
    <mirrorOf>JDT.LS</mirrorOf>
    <url>https://download.eclipse.org/jdtls/milestones/1.12.0/repository/</url>
    <layout>p2</layout>
    <mirrorOfLayouts>p2</mirrorOfLayouts>
  </mirror>
```

**Comment by testforstephen** [comment]
Closed with PR https://github.com/microsoft/java-debug/pull/420.
