### ISSUE TITLE
References to launch.json in error messaging may be misleading

### ISSUE THREAD

**Issue by robstryker** [microsoft/java-debug#431]
https://github.com/microsoft/java-debug/search?q=launch.json

There appear to be only two references to launch.json in this repository. There does not appear to be any part of the code actually reading or referencing or introspecting a file named launch.json. 

End users may find references to launch.json confusing if a third party tool has launched the debugger to connect to a java process and did not pass in a "projectName" to the call. While I realize this is a bit outside the scope of this repository, an example would be a vscode extension using the vscode.debug API (which flows to the https://github.com/microsoft/vscode-java-debug extension) and not setting a project name. In this case there is no launch.json file. 

```
private async startDebugger(port: string) {
        this.port = port;
        vscode.debug.startDebugging(undefined, {
            type: 'java',
            request: 'attach',
            name: 'Debug (Remote)',
            hostName: 'localhost',
            port,
           projectName // set to undefined as an example
        });
    }
```

Since this repository itself does not read a launch.json at all, and all configuration is passed in via a Debug Adapter, not an existing file, these references to a file name are very misleading.

**Comment by rgrunber** [comment]
I would guess, such users would see the debug session launch just fine, but the moment they try to hover over an expression or perform some evaluation they would see :

```
!ENTRY java-debug 4 0 2025-04-09 11:32:04.911
!MESSAGE [error response][evaluate]: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
!STACK 0
com.microsoft.java.debug.core.DebugException: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:266)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:180)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByType(JdtEvaluationProvider.java:299)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:419)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:141)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:116)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:90)
	... 7 more
```

I guess the real issue is one of documentation/visibility. It's mentioned at https://github.com/microsoft/vscode-java-debug?tab=readme-ov-file#attach :

>**projectName** - The preferred project in which the debugger searches for classes. There could be duplicated class names in different projects. It is required when the workspace has multiple java projects, otherwise the expression evaluation and conditional breakpoint may not work.
