### ISSUE TITLE
[VMDisconnectedException]Got IOException from Virtual Machine on ConfigurationDone request

### ISSUE THREAD

**Issue by andxu** [Microsoft/java-debug#53]
![image](https://user-images.githubusercontent.com/17075863/30944161-9c05dfb4-a428-11e7-87c3-821a117e654c.png)

com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90) at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187) at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227) at org.eclipse.jdi.internal.request.EventRequestImpl.enable(EventRequestImpl.java:258) at com.microsoft.java.debug.core.DebugSession.start(DebugSession.java:36) at com.microsoft.java.debug.core.adapter.handler.ConfigurationDoneRequestHandler.handle(ConfigurationDoneRequestHandler.java:54) at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:73) at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:208) at com.microsoft.java.debug.core.adapter.ProtocolServer.processData(ProtocolServer.java:177) at com.microsoft.java.debug.core.adapter.ProtocolServer.start(ProtocolServer.java:99) at com.microsoft.java.debug.plugin.internal.JavaDebugServer$2.run(JavaDebugServer.java:139) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/104
